[build-system]
requires = ['setuptools>=61', 'wheel']

[project]
name = 'reconal'
description = 'Interferometric event reconstruction with scalar-eikonal solvers'
readme = 'README.md'
version = '0.0.0'
requires-python = '>= 3.11'
dependencies = ['Cython==3.0.11',
                'h5py==3.12.1',
                'numpy==2.1.3',
                'scipy==1.14.1',
                'pykonal @ git+https://github.com/mcb28/pykonal.git']

[project.urls]
'Homepage' = 'https://github.com/philippwindischhofer/Reconal'

[tool.setuptools]
packages = ['reconal']